/* modlink — 3proxy config generation and child-process lifecycle.
 *
 * Why 3proxy instead of sing-box: the `auto` service (added in 3proxy 0.9.5)
 * autodetects HTTP CONNECT vs SOCKS on a single port, which is exactly what
 * sing-box's `mixed` inbound did — but the whole binary is ~1.8 MB instead of
 * ~30 MB, so it ships embedded in this .exe as a resource.
 *
 * Per modem the generated config is three lines:
 *      flush
 *      allow <login>
 *      auto -p<port> -i<listen_ip> -e<lan_ip>
 * `flush` clears the accumulated ACL list, so each service gets exactly one
 * allowed user and modems cannot borrow each other's outbound interface.
 */
#include "common.h"
#include "json.h"
#include <string.h>
#include <stdlib.h>

#define IDR_3PROXY_EXE 101

static HANDLE g_proc = NULL;
static HANDLE g_job  = NULL;
static CRITICAL_SECTION g_cs;
static BOOL   g_cs_ready = FALSE;

static void p3_lock_init(void)
{
    if (!g_cs_ready) { InitializeCriticalSection(&g_cs); g_cs_ready = TRUE; }
}

/* ------------------------------------------------------- embedded binary */
/* The exe carries 3proxy.exe as an RCDATA resource and drops it next to the
 * config on first run. Re-extracted whenever the size differs, which is enough
 * to catch "modlink was updated and ships a newer 3proxy". */
BOOL p3_extract_binary(void)
{
    HRSRC   res;
    HGLOBAL glob;
    const void *data;
    DWORD   size;
    HANDLE  h;
    DWORD   wrote = 0;
    WIN32_FILE_ATTRIBUTE_DATA fad;

    ml_ensure_dirs();

    res = FindResourceW(NULL, MAKEINTRESOURCEW(IDR_3PROXY_EXE), RT_RCDATA);
    if (!res) {
        /* Not fatal: a developer build may rely on a manually placed exe. */
        if (GetFileAttributesA(ml_path_3pexe()) != INVALID_FILE_ATTRIBUTES) {
            ml_log("3proxy: no embedded resource, using existing %s", ml_path_3pexe());
            return TRUE;
        }
        ml_log("3proxy: embedded resource missing and no %s on disk", ml_path_3pexe());
        return FALSE;
    }

    size = SizeofResource(NULL, res);
    glob = LoadResource(NULL, res);
    if (!glob || !size) return FALSE;
    data = LockResource(glob);
    if (!data) return FALSE;

    if (GetFileAttributesExA(ml_path_3pexe(), GetFileExInfoStandard, &fad) &&
        fad.nFileSizeLow == size && fad.nFileSizeHigh == 0)
        return TRUE;                        /* already the right build */

    h = CreateFileA(ml_path_3pexe(), GENERIC_WRITE, 0, NULL,
                    CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);
    if (h == INVALID_HANDLE_VALUE) {
        ml_log("3proxy: cannot write %s (err %lu)", ml_path_3pexe(), GetLastError());
        return FALSE;
    }
    WriteFile(h, data, size, &wrote, NULL);
    CloseHandle(h);

    if (wrote != size) { ml_log("3proxy: short write extracting binary"); return FALSE; }
    ml_log("3proxy: extracted %lu bytes -> %s", (unsigned long)size, ml_path_3pexe());
    return TRUE;
}

/* ------------------------------------------------------- config generation */
/* 3proxy treats a leading '$' as "include this file", and splits on whitespace,
 * so every user-supplied token is emitted inside double quotes. */
static void append_quoted(JBuf *b, const char *s)
{
    jb_raw(b, "\"");
    for (; s && *s; s++) {
        if (*s == '"') jb_raw(b, "\\\"");
        else { char t[2]; t[0] = *s; t[1] = 0; jb_raw(b, t); }
    }
    jb_raw(b, "\"");
}

BOOL p3_write_config(const Config *c, char *err, size_t errcap)
{
    JBuf b;
    char line[1024];
    int i, services = 0;
    BOOL ok;

    if (err && errcap) err[0] = 0;
    ml_ensure_dirs();

    jb_init(&b);
    jb_raw(&b, "# generated by modlink - do not edit, changes are overwritten\n\n");

    /* Resolve names through the modem's own path, not the host resolver, and
     * cache so repeated lookups do not hit the LTE link. */
    jb_raw(&b, "nserver 8.8.8.8\n");
    jb_raw(&b, "nserver 1.1.1.1\n");
    jb_raw(&b, "nscache 65536\n");
    jb_raw(&b, "timeouts 1 5 30 60 180 1800 15 60\n");

    snprintf(line, sizeof(line), "log \"%s\" D\n", ml_path_3plog());
    jb_raw(&b, line);
    jb_raw(&b, "rotate 7\n");
    jb_raw(&b, "logformat \"- +_L%d-%m-%Y %H:%M:%S %N.%p %E %U %C:%c %R:%r %O %I %T\"\n\n");

    /* auth strong = username+password required; an unknown user is rejected
     * regardless of ACLs. */
    jb_raw(&b, "auth strong\n");
    jb_raw(&b, "users");
    for (i = 0; i < c->count; i++) {
        const Modem *m = &c->modems[i];
        if (!m->enabled || !m->login[0] || !m->pass[0]) continue;
        jb_raw(&b, " ");
        {
            char tok[ML_LOGIN_LEN + ML_PASS_LEN + 8];
            snprintf(tok, sizeof(tok), "%s:CL:%s", m->login, m->pass);
            append_quoted(&b, tok);
        }
    }
    jb_raw(&b, "\n\n");

    for (i = 0; i < c->count; i++) {
        const Modem *m = &c->modems[i];
        if (!m->enabled || !m->login[0] || !ml_port_valid(m->proxy_port)) continue;

        jb_raw(&b, "flush\n");
        jb_raw(&b, "allow ");
        jb_raw(&b, m->login);
        jb_raw(&b, "\n");

        /* -p listen port, -i listen address, -e outbound bind address.
         * -e is the modem's interface on this host: it is what actually pins
         * this port's traffic to that LTE link.
         * SO_EXCLUSIVEADDRUSE stops another local process from stealing the
         * port behind our back (Windows does not set SO_REUSEADDR here). */
        snprintf(line, sizeof(line), "auto -p%d", m->proxy_port);
        jb_raw(&b, line);
        if (m->listen_ip[0]) { snprintf(line, sizeof(line), " -i%s", m->listen_ip); jb_raw(&b, line); }
        if (m->lan_ip[0])    { snprintf(line, sizeof(line), " -e%s", m->lan_ip);    jb_raw(&b, line); }
        jb_raw(&b, " -olSO_EXCLUSIVEADDRUSE\n\n");
        services++;
    }

    if (!services) {
        if (err) ml_strlcpy(err, "Нет ни одного активного модема с корректным портом", errcap);
        jb_free(&b);
        return FALSE;
    }

    ok = b.buf ? ml_write_file_atomic(ml_path_3pcfg(), b.buf, b.len) : FALSE;
    jb_free(&b);
    if (!ok && err) snprintf(err, errcap, "Не удалось записать %s", ml_path_3pcfg());
    if (ok) ml_log("3proxy config written: %d services", services);
    return ok;
}

/* ------------------------------------------------------- process control */
BOOL p3_running(void)
{
    BOOL alive;
    p3_lock_init();
    EnterCriticalSection(&g_cs);
    alive = g_proc && WaitForSingleObject(g_proc, 0) == WAIT_TIMEOUT;
    LeaveCriticalSection(&g_cs);
    return alive;
}

void p3_stop(void)
{
    p3_lock_init();
    EnterCriticalSection(&g_cs);
    if (g_proc) {
        TerminateProcess(g_proc, 0);
        WaitForSingleObject(g_proc, 3000);
        CloseHandle(g_proc);
        g_proc = NULL;
        ml_log("3proxy stopped");
    }
    LeaveCriticalSection(&g_cs);
}

BOOL p3_start(char *err, size_t errcap)
{
    STARTUPINFOA si;
    PROCESS_INFORMATION pi;
    char cmd[ML_PATH_LEN * 2];
    BOOL ok;

    if (err && errcap) err[0] = 0;
    p3_stop();
    p3_lock_init();

    if (GetFileAttributesA(ml_path_3pexe()) == INVALID_FILE_ATTRIBUTES) {
        if (!p3_extract_binary()) {
            if (err) snprintf(err, errcap, "3proxy.exe отсутствует (%s)", ml_path_3pexe());
            return FALSE;
        }
    }

    /* A job object with KILL_ON_JOB_CLOSE guarantees 3proxy dies with us even
     * on a hard kill of the panel — the Python version leaked processes and
     * had to fall back to `taskkill /F /IM`. */
    EnterCriticalSection(&g_cs);
    if (!g_job) {
        JOBOBJECT_EXTENDED_LIMIT_INFORMATION jeli;
        g_job = CreateJobObjectA(NULL, NULL);
        if (g_job) {
            memset(&jeli, 0, sizeof(jeli));
            jeli.BasicLimitInformation.LimitFlags = JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE;
            SetInformationJobObject(g_job, JobObjectExtendedLimitInformation,
                                    &jeli, sizeof(jeli));
        }
    }
    LeaveCriticalSection(&g_cs);

    memset(&si, 0, sizeof(si));
    si.cb = sizeof(si);
    memset(&pi, 0, sizeof(pi));
    snprintf(cmd, sizeof(cmd), "\"%s\" \"%s\"", ml_path_3pexe(), ml_path_3pcfg());

    ok = CreateProcessA(NULL, cmd, NULL, NULL, FALSE,
                        CREATE_NO_WINDOW | CREATE_SUSPENDED,
                        NULL, ml_dir_data(), &si, &pi);
    if (!ok) {
        if (err) snprintf(err, errcap, "Не удалось запустить 3proxy (ошибка %lu)", GetLastError());
        ml_log("3proxy CreateProcess failed: %lu", GetLastError());
        return FALSE;
    }

    if (g_job) AssignProcessToJobObject(g_job, pi.hProcess);
    ResumeThread(pi.hThread);
    CloseHandle(pi.hThread);

    EnterCriticalSection(&g_cs);
    g_proc = pi.hProcess;
    LeaveCriticalSection(&g_cs);

    /* 3proxy exits immediately on a bad config or a port it cannot bind, so a
     * short wait separates "started" from "died on startup". */
    if (WaitForSingleObject(pi.hProcess, 700) == WAIT_OBJECT_0) {
        DWORD code = 1;
        char **lines = NULL;
        int n, i;
        GetExitCodeProcess(pi.hProcess, &code);

        n = ml_tail_file(ml_path_3plog(), 6, &lines);
        if (err && errcap) {
            size_t used = (size_t)snprintf(err, errcap,
                "3proxy завершился сразу (код %lu). Обычно это занятый порт или неверный -e адрес.", code);
            for (i = 0; i < n && used + 2 < errcap; i++)
                used += (size_t)snprintf(err + used, errcap - used, "\n%s", lines[i]);
        }
        ml_free_lines(lines, n);
        ml_log("3proxy died on startup, exit code %lu", code);
        p3_stop();
        return FALSE;
    }

    ml_log("3proxy started (pid %lu)", pi.dwProcessId);
    return TRUE;
}

BOOL p3_apply(const Config *c, char *err, size_t errcap)
{
    if (!p3_write_config(c, err, errcap)) return FALSE;
    return p3_start(err, errcap);
}
